-- ==========================================
-- Classico SaaS - SECURE Supabase Setup Script
-- ==========================================

-- 1. Subscriptions Table (Current Status)
CREATE TABLE IF NOT EXISTS subscriptions (
    client_id SERIAL,
    machine_id TEXT PRIMARY KEY,
    status TEXT DEFAULT 'pending',
    plan_type TEXT,
    expires_at TIMESTAMP WITH TIME ZONE,
    device_limit INTEGER DEFAULT 20,
    max_devices INTEGER DEFAULT 1,
    phone_number TEXT,
    activation_keys JSONB DEFAULT '[]',
    proof_url TEXT,
    amount INTEGER DEFAULT 0,
    payment_method TEXT,
    transaction_id TEXT,
    last_heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    activated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure columns exist if table was already created
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='amount') THEN
        ALTER TABLE subscriptions ADD COLUMN amount INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='payment_method') THEN
        ALTER TABLE subscriptions ADD COLUMN payment_method TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='transaction_id') THEN
        ALTER TABLE subscriptions ADD COLUMN transaction_id TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='phone_number') THEN
        ALTER TABLE subscriptions ADD COLUMN phone_number TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='max_devices') THEN
        ALTER TABLE subscriptions ADD COLUMN max_devices INTEGER DEFAULT 1;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='activation_keys') THEN
        ALTER TABLE subscriptions ADD COLUMN activation_keys JSONB DEFAULT '[]';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscriptions' AND COLUMN_NAME='activated_at') THEN
        ALTER TABLE subscriptions ADD COLUMN activated_at TIMESTAMP WITH TIME ZONE;
    END IF;
END $$;

-- 2. Cloud Backups Table (Data Safety)
CREATE TABLE IF NOT EXISTS cloud_backups (
    machine_id TEXT PRIMARY KEY,
    data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Subscription Logs Table (Permanent History)
CREATE TABLE IF NOT EXISTS subscription_logs (
    id SERIAL PRIMARY KEY,
    machine_id TEXT NOT NULL,
    plan_type TEXT,
    status TEXT, -- active, expired, cancelled
    action TEXT, -- approved, rejected, deleted
    activated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure action column exists if table was already created
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscription_logs' AND COLUMN_NAME='action') THEN
        ALTER TABLE subscription_logs ADD COLUMN action TEXT;
    END IF;
END $$;

-- 7. Table for Multi-Device License Keys
CREATE TABLE IF NOT EXISTS subscription_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_machine_id TEXT NOT NULL, -- The machine_id of the primary subscriber
    serial_key TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'unused', -- 'unused', 'used'
    used_by TEXT, -- machine_id of the sub-device
    device_name TEXT, -- اسم الجهاز/الفرع
    activated_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure device_name column exists if table was already created
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='subscription_keys' AND COLUMN_NAME='device_name') THEN
        ALTER TABLE subscription_keys ADD COLUMN device_name TEXT;
    END IF;
END $$;

-- 4. Enable RLS on all tables
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE cloud_backups ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_keys ENABLE ROW LEVEL SECURITY;

-- 5. Granular Policies for Subscriptions
DROP POLICY IF EXISTS "Allow anonymous full access" ON subscriptions;
DROP POLICY IF EXISTS "Devices can view own subscription" ON subscriptions;
DROP POLICY IF EXISTS "Allow new registration" ON subscriptions;
DROP POLICY IF EXISTS "No anonymous updates to sensitive fields" ON subscriptions;
DROP POLICY IF EXISTS "Owner full access" ON subscriptions;
DROP POLICY IF EXISTS "Allow anonymous updates for pending requests" ON subscriptions;
DROP POLICY IF EXISTS "Allow server to activate subscriptions" ON subscriptions;
DROP POLICY IF EXISTS "Allow public delete subscriptions" ON subscriptions;
DROP POLICY IF EXISTS "Allow public update subscriptions" ON subscriptions;

-- Owner has absolute access (authenticated via email)
CREATE POLICY "Owner full access" ON subscriptions 
FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com')
WITH CHECK (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com');

-- Read is open to support multi-device validation smoothly (exposes basic info for phone checking)
CREATE POLICY "Devices can view own subscription" ON subscriptions 
FOR SELECT TO anon 
USING (true); 

-- Devices can ONLY create pending subscriptions for their own machine ID
CREATE POLICY "Allow new registration" ON subscriptions 
FOR INSERT TO anon 
WITH CHECK (
    status = 'pending' AND 
    machine_id = (current_setting('request.headers', true)::json->>'x-machine-id')
);

-- Devices can update their own heartbeat but CANNOT manipulate status or expiration
CREATE POLICY "Allow public update subscriptions" ON subscriptions 
FOR UPDATE TO anon 
USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))
WITH CHECK (
    machine_id = (current_setting('request.headers', true)::json->>'x-machine-id') AND
    (status = (SELECT status FROM subscriptions WHERE machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))) AND
    (expires_at = (SELECT expires_at FROM subscriptions WHERE machine_id = (current_setting('request.headers', true)::json->>'x-machine-id')))
);

-- Devices can delete their own subscription
CREATE POLICY "Allow public delete subscriptions" ON subscriptions 
FOR DELETE TO anon 
USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));

-- 6. Granular Policies for Cloud Backups
DROP POLICY IF EXISTS "Enable backup management" ON cloud_backups;
DROP POLICY IF EXISTS "Owner backup access" ON cloud_backups;
DROP POLICY IF EXISTS "Devices can manage own backups" ON cloud_backups;

-- Allow devices to manage their own backups
CREATE POLICY "Devices can manage own backups" ON cloud_backups 
FOR ALL TO anon 
USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))
WITH CHECK (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));

-- Allow Owner to view/manage all backups
CREATE POLICY "Owner backup access" ON cloud_backups FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com')
WITH CHECK (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com');

-- 6b. Granular Policies for Subscription Logs
DROP POLICY IF EXISTS "Enable logs read/write for all" ON subscription_logs;
DROP POLICY IF EXISTS "Allow public insert logs" ON subscription_logs;
DROP POLICY IF EXISTS "Devices can insert logs" ON subscription_logs;
DROP POLICY IF EXISTS "Devices can view own logs" ON subscription_logs;

CREATE POLICY "Devices can view own logs" ON subscription_logs 
FOR SELECT TO anon 
USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));

CREATE POLICY "Devices can insert logs" ON subscription_logs 
FOR INSERT TO anon 
WITH CHECK (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));

-- Policies for Keys
DROP POLICY IF EXISTS "Public view for verification" ON subscription_keys;
DROP POLICY IF EXISTS "Public update for binding" ON subscription_keys;
DROP POLICY IF EXISTS "Owner manage keys" ON subscription_keys;
DROP POLICY IF EXISTS "Server manage keys" ON subscription_keys;
DROP POLICY IF EXISTS "Allow public delete keys" ON subscription_keys;
DROP POLICY IF EXISTS "Devices can select keys" ON subscription_keys;
DROP POLICY IF EXISTS "Devices can update own keys" ON subscription_keys;

CREATE POLICY "Owner manage keys" ON subscription_keys FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com')
WITH CHECK (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com');

CREATE POLICY "Devices can select keys" ON subscription_keys 
FOR SELECT TO anon 
USING (
    status = 'unused' OR 
    used_by = (current_setting('request.headers', true)::json->>'x-machine-id') OR 
    owner_machine_id = (current_setting('request.headers', true)::json->>'x-machine-id')
);

CREATE POLICY "Devices can update own keys" ON subscription_keys 
FOR UPDATE TO anon 
USING (
    status = 'unused' OR 
    owner_machine_id = (current_setting('request.headers', true)::json->>'x-machine-id')
) 
WITH CHECK (
    used_by = (current_setting('request.headers', true)::json->>'x-machine-id') OR 
    owner_machine_id = (current_setting('request.headers', true)::json->>'x-machine-id')
);



-- ==========================================================
-- SECURE PUBLIC TOURNAMENT REGISTRATION RPC FUNCTIONS
-- ==========================================================

-- Function 1: Fetch sanitized tournament details for public registration (No financial leak)
CREATE OR REPLACE FUNCTION get_public_tournament(target_machine_id TEXT, target_tournament_id TEXT)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    backup_data JSONB;
    tour_item JSONB;
    found_tour JSONB;
BEGIN
    SELECT data INTO backup_data FROM cloud_backups WHERE machine_id = target_machine_id;
    IF backup_data IS NULL THEN
        RETURN NULL;
    END IF;

    found_tour := NULL;

    FOR tour_item IN SELECT jsonb_array_elements(backup_data->'classico_tournaments') LOOP
        IF target_tournament_id IS NOT NULL AND target_tournament_id != '' THEN
            IF tour_item->>'id' = target_tournament_id THEN
                found_tour := tour_item;
                EXIT;
            END IF;
        ELSE
            -- No ID specified, find the first in 'registration' status, or 'active', or fallback to the last one
            IF tour_item->>'status' = 'registration' THEN
                found_tour := tour_item;
                EXIT;
            ELSIF tour_item->>'status' = 'active' AND found_tour IS NULL THEN
                found_tour := tour_item;
            ELSIF found_tour IS NULL THEN
                found_tour := tour_item;
            END IF;
        END IF;
    END LOOP;

    IF found_tour IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN jsonb_build_object(
        'id', found_tour->'id',
        'name', found_tour->'name',
        'appName', COALESCE(backup_data->'classico_app_settings'->>'appName', 'كلاسيكو'),
        'fee', found_tour->'fee',
        'maxPlayers', found_tour->'maxPlayers',
        'type', found_tour->'type',
        'status', found_tour->'status',
        'prizes', found_tour->'prizes',
        'prizesList', found_tour->'prizesList',
        'paymentMethod', found_tour->'paymentMethod',
        'paymentNumberCash', found_tour->'paymentNumberCash',
        'paymentNumberInstapay', found_tour->'paymentNumberInstapay',
        'paymentNumberWallet', found_tour->'paymentNumberWallet',
        'players', (
            SELECT COALESCE(jsonb_agg(
                jsonb_build_object(
                    'id', p->'id',
                    'nickname', p->'nickname',
                    'logoId', p->'logoId',
                    'isPendingApproval', p->'isPendingApproval'
                )
            ), '[]'::jsonb)
            FROM jsonb_array_elements(CASE WHEN jsonb_typeof(found_tour->'players') = 'array' THEN found_tour->'players' ELSE '[]'::jsonb END) p
        )
    );
END;
$$ LANGUAGE plpgsql;


-- Function 3: Secure player login verification (Server-side check to protect phone numbers)
CREATE OR REPLACE FUNCTION verify_player_login(
    target_machine_id TEXT,
    target_tournament_id TEXT,
    input_nickname TEXT,
    input_phone TEXT
)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    backup_data JSONB;
    tour_item JSONB;
    player_item JSONB;
    found_player JSONB := NULL;
    input_nick_low TEXT := lower(trim(input_nickname));
    input_phone_trim TEXT := trim(input_phone);
BEGIN
    SELECT data INTO backup_data FROM cloud_backups WHERE machine_id = target_machine_id;
    IF backup_data IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'لم يتم العثور على بيانات الصالة السحابية.');
    END IF;

    FOR tour_item IN SELECT jsonb_array_elements(backup_data->'classico_tournaments') LOOP
        IF tour_item->>'id' = target_tournament_id THEN
            FOR player_item IN SELECT jsonb_array_elements(tour_item->'players') LOOP
                IF lower(trim(player_item->>'nickname')) = input_nick_low AND 
                   (trim(player_item->>'phone') = input_phone_trim OR player_item->>'phone' = input_phone_trim) THEN
                    found_player := player_item;
                    EXIT;
                END IF;
            END LOOP;
            EXIT;
        END IF;
    END LOOP;

    IF found_player IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'لم يتم العثور على اللاعب. تأكد من الاسم المستعار ورقم الهاتف بدقة.');
    END IF;

    -- Return the full player object including private fields for the logged-in player
    RETURN jsonb_build_object('success', true, 'player', found_player);
END;
$$ LANGUAGE plpgsql;


-- Function 2: Transactional server-side player registration (Handles duplicate check & avoids race conditions)
CREATE OR REPLACE FUNCTION register_public_player(
    target_machine_id TEXT,
    target_tournament_id TEXT,
    new_player JSONB
)
RETURNS JSONB
SECURITY DEFINER
AS $$
DECLARE
    backup_row RECORD;
    backup_data JSONB;
    tournaments_list JSONB;
    tour_item JSONB;
    tour_idx INT;
    players_list JSONB;
    player_item JSONB;
    t_id TEXT;
    max_players INT;
    nickname TEXT;
    phone TEXT;
BEGIN
    -- Select backup row for update to lock it and prevent concurrent registration race conditions
    SELECT * INTO backup_row FROM cloud_backups WHERE machine_id = target_machine_id FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', 'لم يتم العثور على قاعدة بيانات الصالة.');
    END IF;

    backup_data := backup_row.data;
    tournaments_list := backup_data->'classico_tournaments';
    IF tournaments_list IS NULL OR jsonb_array_length(tournaments_list) = 0 THEN
        RETURN jsonb_build_object('success', false, 'message', 'لا توجد بطولات نشطة في الصالة حالياً.');
    END IF;

    -- Find target tournament index
    tour_idx := -1;
    FOR i IN 0..jsonb_array_length(tournaments_list) - 1 LOOP
        tour_item := tournaments_list->i;
        IF tour_item->>'id' = target_tournament_id THEN
            tour_idx := i;
            EXIT;
        END IF;
    END LOOP;

    IF tour_idx = -1 THEN
        RETURN jsonb_build_object('success', false, 'message', 'البطولة غير موجودة أو تم حذفها.');
    END IF;

    tour_item := tournaments_list->tour_idx;
    IF tour_item->>'status' != 'registration' THEN
        RETURN jsonb_build_object('success', false, 'message', 'عذراً، التسجيل في هذه البطولة مغلق حالياً.');
    END IF;

    players_list := tour_item->'players';
    IF players_list IS NULL OR jsonb_typeof(players_list) != 'array' THEN
        players_list := '[]'::jsonb;
    END IF;

    max_players := (tour_item->>'maxPlayers')::int;
    IF jsonb_array_length(players_list) >= max_players THEN
        RETURN jsonb_build_object('success', false, 'message', 'عذراً، البطولة مكتملة العدد بالفعل ولا يمكن قبول تسجيل إضافي.');
    END IF;

    -- Uniqueness Validation
    nickname := lower(trim(new_player->>'nickname'));
    phone := trim(new_player->>'phone');

    FOR i IN 0..jsonb_array_length(players_list) - 1 LOOP
        player_item := players_list->i;
        IF lower(trim(player_item->>'nickname')) = nickname THEN
            RETURN jsonb_build_object('success', false, 'message', 'هذا الاسم المستعار مسجل بالفعل! يرجى اختيار اسم مستعار آخر.');
        END IF;
        IF trim(player_item->>'phone') = phone THEN
            RETURN jsonb_build_object('success', false, 'message', 'رقم الهاتف هذا مسجل بالفعل في هذه البطولة!');
        END IF;
        IF (player_item->>'logoId')::int = (new_player->>'logoId')::int THEN
            RETURN jsonb_build_object('success', false, 'message', 'هذا الشعار محجوز بالفعل في هذه البطولة! يرجى اختيار شعار آخر.');
        END IF;
    END LOOP;

    -- Append new player to array
    players_list := players_list || jsonb_build_array(new_player);
    tour_item := jsonb_set(tour_item, '{players}', players_list);
    
    -- Put back updated tournament in list
    tournaments_list := jsonb_set(tournaments_list, array[tour_idx::text], tour_item);
    backup_data := jsonb_set(backup_data, '{classico_tournaments}', tournaments_list);

    -- Write back and save
    UPDATE cloud_backups 
    SET data = backup_data, updated_at = NOW() 
    WHERE machine_id = target_machine_id;

    -- Return success and sanitized tournament object for UI sync
    RETURN jsonb_build_object(
        'success', true, 
        'message', 'تم التسجيل بنجاح!', 
        'tournament', jsonb_build_object(
            'id', tour_item->'id',
            'name', tour_item->'name',
            'appName', COALESCE(backup_data->'classico_app_settings'->>'appName', 'كلاسيكو'),
            'fee', tour_item->'fee',
            'maxPlayers', tour_item->'maxPlayers',
            'type', tour_item->'type',
            'status', tour_item->'status',
            'prizes', tour_item->'prizes',
            'prizesList', tour_item->'prizesList',
            'paymentMethod', tour_item->'paymentMethod',
            'paymentNumberCash', tour_item->'paymentNumberCash',
            'paymentNumberInstapay', tour_item->'paymentNumberInstapay',
            'paymentNumberWallet', tour_item->'paymentNumberWallet',
            'players', (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'id', p->'id',
                        'nickname', p->'nickname',
                        'logoId', p->'logoId',
                        'isPendingApproval', p->'isPendingApproval'
                    )
                )
                FROM jsonb_array_elements(tour_item->'players') p
            )
        )
    );
END;
$$ LANGUAGE plpgsql;


-- ==========================================================
-- LINTER & SECURITY HARDENING FIXES
-- ==========================================================

-- 1. Enable RLS on tables that have policies but RLS is currently disabled (Red Linter Errors)
ALTER TABLE IF EXISTS public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payment_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;

-- 1b. Restrict Admin policies to the owner email to solve the Permissive RLS warnings
DROP POLICY IF EXISTS "Admin_Full_Access" ON public.profiles;
CREATE POLICY "Admin_Full_Access" ON public.profiles 
FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com')
WITH CHECK (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com');

DROP POLICY IF EXISTS "Admin_Full_Access_Devices" ON public.devices;
CREATE POLICY "Admin_Full_Access_Devices" ON public.devices 
FOR ALL TO authenticated
USING (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com')
WITH CHECK (auth.jwt() ->> 'email' = 'emontal.33@yahoo.com');


-- 2. Fix search path for all custom functions to prevent search path hijacking (Yellow Linter Warnings)
ALTER FUNCTION public.generate_unique_short_id() SET search_path = public;
ALTER FUNCTION public.set_short_id() SET search_path = public;
ALTER FUNCTION public.has_backup_access(text, text) SET search_path = public;
ALTER FUNCTION public.register_public_player(text, text, jsonb) SET search_path = public;
ALTER FUNCTION public.get_public_tournament(text, text) SET search_path = public;
ALTER FUNCTION public.verify_player_login(text, text, text, text) SET search_path = public;

-- 3. Secure SECURITY DEFINER functions by revoking public execute and granting only to specific roles (Yellow Linter Warnings)
REVOKE EXECUTE ON FUNCTION public.has_backup_access(text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.has_backup_access(text, text) TO anon, authenticated, service_role;

REVOKE EXECUTE ON FUNCTION public.register_public_player(text, text, jsonb) FROM public;
GRANT EXECUTE ON FUNCTION public.register_public_player(text, text, jsonb) TO anon, authenticated, service_role;

REVOKE EXECUTE ON FUNCTION public.get_public_tournament(text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.get_public_tournament(text, text) TO anon, authenticated, service_role;

REVOKE EXECUTE ON FUNCTION public.verify_player_login(text, text, text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.verify_player_login(text, text, text, text) TO anon, authenticated, service_role;

-- 4. Secure legacy sync tables RLS policies if columns exist (Yellow Linter Warnings)
DO $$
BEGIN
    -- For sync_history
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sync_history' AND column_name = 'machine_id') THEN
        DROP POLICY IF EXISTS "Allow anonymous upsert" ON sync_history;
        CREATE POLICY "Allow anonymous upsert" ON sync_history FOR ALL TO anon
        USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))
        WITH CHECK (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));
    END IF;
    
    -- For sync_lounge_history
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sync_lounge_history' AND column_name = 'machine_id') THEN
        DROP POLICY IF EXISTS "Allow anonymous upsert" ON sync_lounge_history;
        CREATE POLICY "Allow anonymous upsert" ON sync_lounge_history FOR ALL TO anon
        USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))
        WITH CHECK (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));
    END IF;

    -- For sync_users
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'sync_users' AND column_name = 'machine_id') THEN
        DROP POLICY IF EXISTS "Allow anonymous access" ON sync_users;
        CREATE POLICY "Allow anonymous access" ON sync_users FOR ALL TO anon
        USING (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'))
        WITH CHECK (machine_id = (current_setting('request.headers', true)::json->>'x-machine-id'));
    END IF;
END $$;
